# Generated by Django 4.1.2 on 2022-10-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_notes_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='bookmark',
            field=models.IntegerField(default=0),
        ),
    ]
